'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),fmt=n=>n.toLocaleString('en-GB');
const TYPES={treatment:['Treatment plants','#b15388'],river:['Rivers','#267fab'],stream:['Streams','#69a8c2'],lake:['Lakes','#1978bb'],reservoir:['Reservoirs','#23659f'],pond:['Ponds','#48a6b5'],lagoon:['Lagoons','#318d92'],wetland:['Wetlands','#65a58d'],canal:['Canals / drains','#8b98b3'],coastal:['Coastal / salt water','#5597a8'],wastewater:['Wastewater-tagged','#b28b66'],other_water:['Other water','#9baec2'],other_feature:['Other mapped features','#8d8d91']};
const DEFAULT=new Set(Object.keys(TYPES).filter(k=>k!=='other_feature'));let selectedTypes=new Set(['treatment','wastewater']),index,records=[],byId=new Map(),matches=[],limit=35,selected=null,generation=0,hitPaths=[],loadErrors=0;const cache=new Map(),pending=new Map();
const REGIONS={mainland:[[36.9,-9.6],[42.2,-6.1]],azores:[[36.8,-31.4],[40,-24.7]],madeira:[[30,-17.5],[33.3,-15.7]],all:[[30,-31.5],[42.3,-6]]};
const map=L.map('map',{zoomControl:false,minZoom:4,maxZoom:18,preferCanvas:true}).fitBounds(REGIONS.mainland);L.control.zoom({position:'topright'}).addTo(map);L.control.scale({imperial:false,position:'bottomright'}).addTo(map);
const base=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors · water extract: <a href="https://data.humdata.org/dataset/hotosm_prt_waterways">HOT / HDX</a>'}).addTo(map);let baseError=false;base.on('tileerror',()=>{baseError=true;});
map.attributionControl.addAttribution('Facilities: <a href="https://www.eea.europa.eu/en/datahub/datahubitem-view/6ffd0af1-64eb-4cce-9970-0028e01ee64e">EEA / UWWTD</a>');
const canvas=L.DomUtil.create('canvas','watercanvas',map.getPanes().overlayPane),ctx=canvas.getContext('2d');
for(const [k,[name,color]] of Object.entries(TYPES)){const lab=document.createElement('label');lab.className='type';lab.innerHTML=`<input type="checkbox" value="${k}" ${selectedTypes.has(k)?'checked':''}><span class="dot" style="background:${color}"></span>${name}`;lab.querySelector('input').addEventListener('change',e=>{e.target.checked?selectedTypes.add(k):selectedTypes.delete(k);filter();});$('types').append(lab);}
async function jsonGzip(path){const r=await fetch(path);if(!r.ok)throw Error('Could not load '+path);if(!window.DecompressionStream)throw Error('This browser needs gzip DecompressionStream support. Use a current Chrome, Edge, Firefox or Safari.');return await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();}
function intersects(a,b){return a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1];}
function viewBox(){const b=map.getBounds();return [b.getWest(),b.getSouth(),b.getEast(),b.getNorth()];}
function accepts(r){const q=norm($('search').value.trim());return selectedTypes.has(r.kind)&&($('region').value==='all'||r.region===$('region').value)&&(!q||r.search.includes(q));}
function filter(){if(!index)return;const low=selectedTypes.has('treatment')||selectedTypes.has('wastewater');$('lowgradeNotice').hidden=!low;$('lowgradePreset').setAttribute('aria-pressed',String(selectedTypes.size===2&&selectedTypes.has('treatment')&&selectedTypes.has('wastewater')));$('waterPreset').setAttribute('aria-pressed',String(selectedTypes.size===DEFAULT.size&&[...DEFAULT].every(k=>selectedTypes.has(k))));if(selected&&!accepts(byId.get(selected))){selected=null;map.closePopup();}limit=35;matches=records.filter(r=>accepts(r)&&(!$('inView').checked||intersects(r.bbox,viewBox())));$('resultCount').textContent=fmt(matches.length)+' matching features';$('export').disabled=!matches.length;list();refresh();}
function list(){const box=$('results');box.replaceChildren();const q=norm($('search').value.trim()),rank=r=>q&&norm(r.name)===q?0:q&&norm(r.name).startsWith(q)?1:r.name?2:3;const shown=matches.slice().sort((a,b)=>rank(a)-rank(b)||a.name.localeCompare(b.name,'pt')).slice(0,limit);for(const r of shown){const button=document.createElement('button');button.className='result';button.innerHTML=`<strong>${esc(r.name||'Unnamed '+TYPES[r.kind][0].toLowerCase())}</strong><small>${esc(TYPES[r.kind][0])} · ${esc(r.place||r.region)} · ${esc(r.id)}</small>`;button.onclick=()=>selectFeature(r);box.append(button);}if(!matches.length)box.innerHTML='<p class="micro">No matching mapped features. Try a different name, region or water type.</p>';$('more').hidden=matches.length<=limit;}
async function tile(file){if(cache.has(file))return cache.get(file);if(pending.has(file))return pending.get(file);const p=jsonGzip('data/'+file).then(a=>{cache.set(file,a);pending.delete(file);return a;}).catch(e=>{pending.delete(file);throw e;});pending.set(file,p);return p;}
async function refresh(){if(!index)return;const gen=++generation,b=viewBox();const todo=index.tiles.filter(t=>intersects(t.bbox,b)&&recordsByTile.has(t.file)&&recordsByTile.get(t.file).some(r=>accepts(r)&&intersects(r.bbox,b)));$('mapStatus').textContent='Loading mapped water geometry…';loadErrors=0;let next=0;await Promise.all(Array.from({length:Math.min(6,todo.length)},async()=>{while(next<todo.length){const t=todo[next++];try{await tile(t.file);}catch(e){loadErrors++;console.error(e.message);}}}));if(gen!==generation)return;draw();}
function line(path,points,close){for(let i=0;i<points.length;i++){const p=map.latLngToContainerPoint([points[i][1],points[i][0]]);i?path.lineTo(p.x,p.y):path.moveTo(p.x,p.y);}if(close)path.closePath();}
function pathFor(g){const p=new Path2D();switch(g.type){case 'Point':{const a=map.latLngToContainerPoint([g.coordinates[1],g.coordinates[0]]);p.arc(a.x,a.y,4,0,Math.PI*2);break;}case 'LineString':line(p,g.coordinates,false);break;case 'MultiLineString':for(const c of g.coordinates)line(p,c,false);break;case 'Polygon':for(const c of g.coordinates)line(p,c,true);break;case 'MultiPolygon':for(const poly of g.coordinates)for(const c of poly)line(p,c,true);break;}return p;}
function draw(){const size=map.getSize(),dpr=devicePixelRatio||1;canvas.width=size.x*dpr;canvas.height=size.y*dpr;canvas.style.width=size.x+'px';canvas.style.height=size.y+'px';L.DomUtil.setPosition(canvas,map.containerPointToLayerPoint([0,0]));ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size.x,size.y);hitPaths=[];const b=viewBox();let visible=0,small=0;const fs=[];for(const a of cache.values())for(const f of a){const r=byId.get(f.id);if(!accepts(r)||!intersects(r.bbox,b))continue;visible++;const p1=map.latLngToContainerPoint([r.bbox[1],r.bbox[0]]),p2=map.latLngToContainerPoint([r.bbox[3],r.bbox[2]]);if(Math.max(Math.abs(p1.x-p2.x),Math.abs(p1.y-p2.y))<2&&r.id!==selected&&r.kind!=='treatment'){small++;continue;}fs.push([f,r]);}fs.sort((a,b)=>Number(a[1].kind==='treatment')-Number(b[1].kind==='treatment')||Number(a[0].geometry.type.includes('Line'))-Number(b[0].geometry.type.includes('Line')));for(const [f,r] of fs){const path=pathFor(f.geometry),area=f.geometry.type.includes('Polygon'),highlight=r.id===selected;ctx.strokeStyle=highlight?'#ef9d32':TYPES[r.kind][1];ctx.fillStyle=highlight?'#ffd899':TYPES[r.kind][1]+'88';ctx.lineWidth=highlight?4:area?1:map.getZoom()>11?1.7:1.1;ctx.lineJoin='round';if(area||f.geometry.type==='Point')ctx.fill(path,'evenodd');ctx.stroke(path);hitPaths.push({path,r,f,area});} $('mapStatus').textContent=loadErrors?'Some water geometry failed to load. Pan or reset to retry.':fmt(visible)+' matching features intersect this view'+(small?' · zoom in for '+fmt(small)+' small features':'')+(baseError?' · basemap unavailable; water layer remains usable':'');}
function popup(r,f,latlng){const tags=f?Object.entries(f.tags).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join(''):'';L.popup({maxWidth:matchMedia('(max-width:650px)').matches?260:310,maxHeight:matchMedia('(max-width:650px)').matches?100:220,autoPanPaddingTopLeft:[12,matchMedia('(max-width:650px)').matches?115:60],autoPanPaddingBottomRight:[12,40]}).setLatLng(latlng||[(r.bbox[1]+r.bbox[3])/2,(r.bbox[0]+r.bbox[2])/2]).setContent(`<h3>${esc(r.name||'Unnamed water feature')}</h3><p><a class="capacityLink" href="capacity.html#id=${encodeURIComponent(r.id)}">Assess hydrogen capacity →</a></p><b>${esc(TYPES[r.kind][0])}</b> · ${esc(r.place||r.region)}<dl>${tags}</dl><a href="${esc(r.sourceUrl||'https://www.openstreetmap.org/'+r.id)}" target="_blank" rel="noopener">${r.kind==='treatment'?'View original EEA record':'View original OSM feature'} ↗</a><p><small>Mapped geometry, not present water level or available supply. Names and tags reflect the source snapshot.</small></p>`).openOn(map);}
async function selectFeature(r){selected=r.id;if(matchMedia('(max-width:650px)').matches)$('map').scrollIntoView({block:'start'});map.fitBounds([[r.bbox[1],r.bbox[0]],[r.bbox[3],r.bbox[2]]],{maxZoom:15,padding:[55,55],animate:false});try{const a=await tile(r.tile);draw();popup(r,a.find(f=>f.id===r.id));}catch(e){$('mapStatus').textContent=e.message;}}
let ignoreMapClickUntil=0;map.on('popupclose',()=>{ignoreMapClickUntil=Date.now()+300;});
map.on('click',e=>{if(Date.now()<ignoreMapClickUntil)return;if(e.originalEvent?.target?.closest('.leaflet-popup,.leaflet-control'))return;const p=e.containerPoint,dpr=devicePixelRatio||1;for(let i=hitPaths.length-1;i>=0;i--){const h=hitPaths[i];ctx.lineWidth=9;if((h.area&&ctx.isPointInPath(h.path,p.x*dpr,p.y*dpr,'evenodd'))||ctx.isPointInStroke(h.path,p.x*dpr,p.y*dpr)){selected=h.r.id;draw();popup(h.r,h.f,e.latlng);break;}}});
map.on('moveend',()=>{if($('inView').checked)filter();else refresh();});map.on('resize',refresh);map.on('zoomstart',()=>canvas.style.visibility='hidden');map.on('zoomend',()=>canvas.style.visibility='');
let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(filter,180);};$('region').onchange=()=>{map.fitBounds(REGIONS[$('region').value]);$('mapRegion').textContent=$('region').selectedOptions[0].text;filter();};$('inView').onchange=filter;$('more').onclick=()=>{limit+=50;list();};$('allTypes').onclick=()=>{selectedTypes=new Set(Object.keys(TYPES));for(const c of $('types').querySelectorAll('input'))c.checked=true;filter();};$('fit').onclick=()=>{if(!matches.length)return;const b=matches.reduce((a,r)=>[Math.min(a[0],r.bbox[0]),Math.min(a[1],r.bbox[1]),Math.max(a[2],r.bbox[2]),Math.max(a[3],r.bbox[3])],[180,90,-180,-90]);map.fitBounds([[b[1],b[0]],[b[3],b[2]]],{padding:[40,40],maxZoom:15});};
$('reset').onclick=()=>{selected=null;$('search').value='';$('region').value='mainland';$('inView').checked=false;selectedTypes=new Set(DEFAULT);for(const c of $('types').querySelectorAll('input'))c.checked=selectedTypes.has(c.value);map.closePopup();map.fitBounds(REGIONS.mainland);$('mapRegion').textContent='Mainland Portugal';filter();};
$('aboutButton').onclick=()=>$('about').showModal();$('closeAbout').onclick=()=>$('about').close();
$('export').onclick=()=>{const quote=v=>'"'+String(typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v).replace(/"/g,'""')+'"';const rows=[['source_id','name','mapped_type','region','municipality','west','south','east','north','source_url','snapshot','license','reuse_availability'],...matches.map(r=>[r.id,r.name,r.kind,r.region,r.place,...r.bbox,r.sourceUrl||'https://www.openstreetmap.org/'+r.id,r.sourceDate||index.sourceDate,r.kind==='treatment'?'EEA standard reuse policy; European Environment Agency':'ODbL 1.0; OpenStreetMap contributors',r.availability||'Not assessed'])];const u=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='portugal-water-inventory.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('exportStatus').textContent='Exported '+fmt(matches.length)+' mapped-feature records with source attribution.';};
const recordsByTile=new Map();
function preset(low){selectedTypes=low?new Set(['treatment','wastewater']):new Set(DEFAULT);for(const c of $('types').querySelectorAll('input'))c.checked=selectedTypes.has(c.value);$('search').value='';filter();}
$('lowgradePreset').onclick=()=>preset(true);$('waterPreset').onclick=()=>preset(false);
Promise.all([jsonGzip('data/index.json.gz'),fetch('data/lowgrade.json').then(r=>{if(!r.ok)throw Error('EEA facility layer unavailable');return r.json();})]).then(([x,lg])=>{index=x;records=[...x.records,...lg.records];cache.set('eea-plants',lg.features);index.tiles.push({file:'eea-plants',bbox:[-32,29,-5,43]});for(const r of records){r.search=norm([r.name,r.place,r.id].join(' '));byId.set(r.id,r);if(!recordsByTile.has(r.tile))recordsByTile.set(r.tile,[]);recordsByTile.get(r.tile).push(r);}$('plantCoverage').textContent='EEA reported plants: '+Object.entries(lg.regions).map(([k,v])=>k+' '+fmt(v)).join(' · ')+'. Missing records do not mean no facilities exist.';$('snapshot').textContent='OSM source dataset interval: '+x.sourceDate+'. EEA report: PT_2022; retrieved '+lg.provenance.retrievedUtc+'. These are snapshots, not live monitoring.';filter();}).catch(e=>{$('mapStatus').textContent=e.message;$('resultCount').textContent='Data could not load';$('results').textContent='Serve this folder over HTTP; do not open it as a file. '+e.message;});
