'use strict';
const C=id=>document.getElementById(id),nf=(n,d=2)=>n===null?'Not established':n.toLocaleString('en-GB',{maximumFractionDigits:d}),e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let feature=null,alternative=null,last=null,demo=false,catalogue=null;
function value(id,nullable=false){const s=C(id).value.trim();if(!s){if(nullable)return null;throw Error('Complete '+C(id).labels[0].textContent);}if(!C(id).checkValidity())throw Error('Check '+C(id).labels[0].textContent);return Number(s);}
function sourceDisplay(){window.refreshPublicEvidence?.();C('sourceName').textContent=demo?'Hypothetical source — example only':feature?(feature.name||'Unnamed mapped feature')+' · '+feature.id:'No mapped feature selected';C('sourceStatus').textContent=demo?'Invented water inputs. This result is not assigned to a real water body.':'Flow, commitments and protected reserves are not established by the map.';C('sourceLink').hidden=!feature||demo;if(feature)C('sourceLink').href=feature.sourceUrl||'https://www.openstreetmap.org/'+feature.id;}
function clearResult(text){last=null;C('numbers').hidden=true;C('export').disabled=true;C('outcome').innerHTML='<strong>Not established</strong><p>'+e(text)+'</p>';}
function sourceInfo(f){return f?{id:f.id,name:f.name,kind:f.kind,url:f.sourceUrl||'https://www.openstreetmap.org/'+f.id}:null;}
function scenario(suffix){
 const c={};for(const id of ['energy','feed','cooling','cf','share','plantMW'])c[id]=value(id);
 c.recovery=value('recovery'+suffix);c.supplyFactor=value('supplyFactor'+suffix);
 const monthly=C('basis'+suffix).value==='monthly',period=C('period'+suffix).value.trim();
 c.periods=monthly?HydrogenCapacity.parseMonthly(C('csv'+suffix).value):[{period:period||'Unspecified dry period',supply:value('supply'+suffix,true),existing:value('existing'+suffix,true),reserve:value('reserve'+suffix,true)}];
 const result=WaterComparison.balance(c),f=suffix?alternative:feature,citation=C('citation'+suffix).value.trim();
 const ready=result.status==='scenario'&&citation&&(f||demo);
 return {source:demo?null:sourceInfo(f),evidenceStatus:demo?'Hypothetical example; no geographic attribution':C('evidence'+suffix).value,citation,inputs:c,result,ready:!!ready,periodSpecified:monthly||!!period};
}
function panel(label,s){const r=s.result;return '<article class="balancePanel"><h3>'+e(label)+' · '+e(demo?'Hypothetical source':s.source?(s.source.name||s.source.id):'No source selected')+'</h3><p class="hint">'+e(s.evidenceStatus)+'</p>'+(s.ready?'<div class="balanceChain"><div>Plant intake<strong>'+nf(r.demand)+' m³/day</strong></div><span>→</span><div>Net water budget<strong>'+nf(r.waterBudget)+' m³/day</strong></div><span>→</span><div>'+e(r.verdict)+'<strong>'+nf(Math.abs(r.margin))+' m³/day</strong></div></div><p>Limiting entered period: '+e(r.limitingPeriod)+'. '+(r.preexistingDeficit?'Existing uses and reserve already exceed supply. ':'')+'Budget = adjusted supply − existing uses − reserve.</p><div class="tablewrap"><table><thead><tr><th>Period</th><th>Adjusted supply</th><th>Existing</th><th>Reserve</th><th>Net budget</th><th>Intake</th><th>Signed margin</th></tr></thead><tbody>'+r.periods.map(p=>'<tr><td>'+e(p.period)+'</td>'+[p.supply,p.existing,p.reserve,p.waterBudget,p.intake,p.margin].map(n=>'<td>'+nf(n)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="hint">All rates m³/day. Evidence and assumptions: '+e(s.citation)+'</p>':'<p><b>Not established.</b> Select a source and provide all water rates plus a flow citation or explicit scenario assumptions. Blank values remain unknown.</p>')+'</article>';}
function sideBySide(a,b){const rows=[['Source',s=>demo?'Hypothetical':s.source?(s.source.name||s.source.id):'Not selected'],['Proposed plant intake (m³/day)',s=>nf(s.result.demand)],['Net water budget (m³/day)',s=>s.ready?nf(s.result.waterBudget):'Not established'],['Signed margin (m³/day)',s=>s.ready?nf(s.result.margin):'Not established'],['Budget outcome',s=>s.ready?s.result.verdict:'Not established'],['Limiting entered period',s=>s.ready?s.result.limitingPeriod:'Not established'],['Recovery assumption (%)',s=>nf(s.inputs.recovery)]];return '<div class="tablewrap"><table><caption>Same proposed plant, separate source scenarios</caption><thead><tr><th>Measure</th><th>Source A</th><th>Source B</th></tr></thead><tbody>'+rows.map(([label,f])=>'<tr><th>'+e(label)+'</th><td>'+e(f(a))+'</td><td>'+e(f(b))+'</td></tr>').join('')+'</tbody></table></div>';}
function calculate(){C('error').hidden=true;try{
 const a=scenario(''),b=scenario('B');let comparison={comparable:false,reason:'Complete both source budgets and evidence before comparing.'};
 if(a.ready&&b.ready){comparison=a.periodSpecified&&b.periodSpecified?WaterComparison.compare(a.result,b.result):{comparable:false,reason:'Specify matching periods for both sources before comparing.'};if(!demo&&feature.id===alternative.id)comparison={comparable:false,reason:'Select two different source records.'};}
 C('balanceResults').innerHTML=sideBySide(a,b)+panel('Source A',a)+panel('Source B',b)+'<div class="outcome"><strong>'+e(comparison.comparable?(comparison.changesBudgetFit?'Changing source changes whether demand fits the entered budget':'Source change does not change budget-fit classification'):'Comparison not established')+'</strong><p>'+e(comparison.reason)+'</p>'+(comparison.comparable?'<p>B minus A limiting margin: '+nf(comparison.marginDifference)+' m³/day. Each source is assessed separately; their supplies are not added.</p>':'')+'</div>';
 last={version:2,sourceA:a,sourceB:b,comparison,limits:'Conditional water-budget screening only. Rights, quality, treatment, conveyance, storage and sub-daily abstraction unverified. Geographic duplicates may exist. A positive margin is not site feasibility.'};
 C('numbers').hidden=false;C('export').disabled=false;
 const r=a.result.result,c=a.inputs;
 C('outcome').innerHTML='<strong>'+e(a.ready?a.result.verdict+' under source A scenario':'Source A budget not established')+'</strong><p>Use the balance above for the proposed plant. The optional share threshold below is a separate user-chosen screening rule.</p>';
 for(const id of ['threshold','fullLoad'])C(id).textContent='Not established';C('chart').innerHTML='';C('periodTable').innerHTML='';C('production').textContent='';C('critical').textContent='';C('proposed').textContent='';
 if(a.ready){C('threshold').textContent=nf(r.thresholdMW,3);C('fullLoad').textContent=nf(r.fullLoadThresholdMW,3);C('critical').textContent='Share-threshold limiting period: '+r.limitingPeriod;C('production').textContent=nf(r.hydrogenKgDay)+' kg H₂/day for the proposed plant.';chart(c,r);}
 }catch(err){clearResult('Correct the inputs to calculate.');C('balanceResults').innerHTML='';C('error').textContent=err.message;C('error').hidden=false;}}
function chart(c,r){const p=r.periods.find(p=>p.period===r.limitingPeriod),maxMW=Math.max(r.thresholdMW*1.6,c.plantMW*1.2,1),maxWater=Math.max(maxMW*r.intakePerMWDay,p.budget*1.3,1),x=MW=>55+MW/maxMW*410,y=w=>215-w/maxWater*165;C('chart').innerHTML=`<svg viewBox="0 0 500 260" role="img" aria-label="Scenario source intake rises linearly with capacity; selected water-share budget is ${e(nf(p.budget))} cubic metres per day"><path class="axis" d="M55 40V215H470"/><path class="demand" d="M55 215L${x(maxMW)} ${y(maxMW*r.intakePerMWDay)}"/><path class="budget" d="M55 ${y(p.budget)}H470"/><circle cx="${x(r.thresholdMW)}" cy="${y(p.budget)}" r="5" fill="#b47642"/><text class="chartlabel" x="60" y="25">Source intake (m³/day)</text><text class="chartlabel" x="65" y="${Math.max(47,y(p.budget)-8)}">Chosen budget: ${nf(p.budget)} m³/day</text><text class="chartlabel" x="55" y="235">0</text><text class="chartlabel" x="370" y="235">${nf(maxMW)} MW</text><text class="chartlabel" x="55" y="255">Period-average electrical nameplate capacity</text></svg>`;}
function invalidate(){C('supplyOut').textContent=C('supplyFactor').value+'%';clearResult('Inputs changed. Calculate to update both results.');C('balanceResults').innerHTML='';C('actionStatus').textContent='';C('error').hidden=true;}
for(const el of document.querySelectorAll('input,textarea,select'))el.addEventListener('input',invalidate);
function showBasis(s){C('single'+s).hidden=C('basis'+s).value==='monthly';C('monthly'+s).hidden=C('basis'+s).value!=='monthly';}
for(const s of ['', 'B'])C('basis'+s).addEventListener('change',()=>showBasis(s));
C('calculate').onclick=calculate;
function clearWater(s){for(const id of ['supply','existing','reserve','citation','csv','period'])C(id+s).value='';C('evidence'+s).selectedIndex=0;C('supplyFactor'+s).value=100;}
function displayB(){window.refreshPublicEvidence?.();C('sourceBStatus').textContent=demo?'Hypothetical source B — invented inputs, no geographic attribution.':alternative?(alternative.name||alternative.id)+' · '+alternative.id+'. Mapped location only; flow unknown.':'Select a mapped source. Its water budget remains unknown.';C('sourceBLink').hidden=demo||!alternative;if(alternative)C('sourceBLink').href=sourceInfo(alternative).url;}
C('example').onclick=()=>{demo=true;for(const s of ['', 'B']){C('basis'+s).value='critical';showBasis(s);C('period'+s).value='Hypothetical dry period';C('existing'+s).value=600;C('reserve'+s).value=200;C('supplyFactor'+s).value=100;C('recovery'+s).value=80;C('evidence'+s).value='Hypothetical scenario';C('citation'+s).value='Invented water budget for demonstration only; no real source attribution.';}C('supply').value=820;C('supplyB').value=1000;for(const [k,v] of Object.entries({energy:55,feed:10,cooling:0,cf:100,share:10,plantMW:5}))C(k).value=v;sourceDisplay();displayB();calculate();};
C('restore').onclick=()=>{demo=false;clearWater('');clearWater('B');sourceDisplay();displayB();invalidate();};
C('sourceB').onchange=()=>{if(demo){demo=false;clearWater('');sourceDisplay();}alternative=catalogue?.find(r=>r.id===C('sourceB').value)||null;clearWater('B');displayB();invalidate();};
C('export').onclick=()=>{if(!last)return;const u=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='hydrogen-water-source-comparison.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);C('actionStatus').textContent='Exported both source identities, separate inputs, evidence status, results and comparison limitations.';};
async function getCatalogue(){if(catalogue)return catalogue;const responses=await Promise.all([fetch('data/index.json.gz'),fetch('data/lowgrade.json')]);if(responses.some(r=>!r.ok))throw Error('Bundled source catalogue unavailable');const [osm,eea]=await Promise.all([new Response(responses[0].body.pipeThrough(new DecompressionStream('gzip'))).json(),responses[1].json()]);catalogue=[...eea.records,...osm.records];return catalogue;}
C('findSource').onclick=async()=>{try{C('findSource').disabled=true;const rows=await getCatalogue(),q=C('sourceSearch').value.trim().toLowerCase();if(!q){C('sourceBStatus').textContent='Enter a source name, ID or place to search.';return;}const matches=rows.filter(r=>r.id!==feature?.id&&[r.name,r.id,r.place,r.kind,r.region].join(' ').toLowerCase().includes(q));C('sourceB').innerHTML='<option value="">Choose an alternative source</option>'+matches.slice(0,50).map(r=>'<option value="'+e(r.id)+'">'+e((r.name||'Unnamed')+' · '+r.kind+' · '+r.id)+'</option>').join('');alternative=null;if(demo){demo=false;clearWater('');sourceDisplay();}clearWater('B');displayB();C('sourceBStatus').textContent=matches.length+' matching records; first 50 shown. Select one to enter its separate budget.';invalidate();}catch(err){C('sourceBStatus').textContent=err.message;}finally{C('findSource').disabled=false;}};
async function load(){try{const id=new URLSearchParams(location.hash.slice(1)).get('id');if(id){feature=(await getCatalogue()).find(r=>r.id===id);if(!feature)throw Error('Feature ID absent from bundled atlas. Choose a source from the map.');}sourceDisplay();}catch(err){C('sourceName').textContent='Source could not be loaded';C('error').hidden=false;C('error').textContent=err.message;}}
load();
