/* Only curated exact source IDs receive linked public evidence. No geographic flow inference. */
(()=>{
 let data=null,receipt=null;
 function intake(s){const n=id=>Number(document.getElementById(id).value),recovery=n('recovery'+s)/100,energy=n('energy'),cf=n('cf')/100,feed=n('feed'),cooling=n('cooling'),mw=n('plantMW');for(const id of ['energy','cf','feed','cooling','plantMW','recovery'+s]){const el=document.getElementById(id);if(!el.value.trim()||!el.checkValidity())throw Error('Complete valid plant inputs to calculate demand.');}return mw*24*cf*(feed/recovery+cooling)/energy;}
 const fmt=n=>n.toLocaleString('en-GB',{maximumFractionDigits:3});
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(){if(!data)return;receipt={version:1,type:'public-evidence-calculation',sources:[],limits:'Historical context only; no established dry-period allocation or feasibility conclusion.'};for(const [suffix,f] of [['',feature],['B',alternative]]){const box=document.getElementById('publicEvidence'+(suffix||'A'));if(demo){box.innerHTML='<h3>Public evidence</h3><p>Hypothetical mode: no public water figures are assigned to this example.</p>';continue;}const record=f?data.records[f.id]:null;if(!record){box.innerHTML='<h3>Automatic public evidence</h3><p>'+(!f?'Select a source.':'No verified flow-budget record is linked to this mapped feature in this release. This does not mean no public data exist.')+'</p><p><b>Available dry-period budget: not established.</b></p>';continue;}
 let result=null,error='';try{result=PublicBudget.assess(record,intake(suffix));}catch(err){error=err.message;}
 receipt.sources.push({mappedId:f.id,evidence:record,plantInputs:Object.fromEntries(['plantMW','energy','cf','feed','cooling','recovery'+suffix].map(id=>[id,document.getElementById(id).value])),calculation:result});
 box.innerHTML='<h2>Automatic public evidence · '+esc(record.name)+'</h2><p><b>Available dry-period budget: not established.</b> Official historical figures are loaded automatically below; required allocation terms are still missing.</p><p>'+esc(record.coverage)+'</p><p><a target="_blank" rel="noopener" href="'+esc(record.source.url)+'#page=20">Official report · page 20, Tables 11 and 13 ↗</a> · <a href="data/public_budget.json">Extracted data and provenance</a> · <a href="PUBLIC_BUDGET_METHOD.md">Calculation method and gaps</a></p><p>Reported annual EFMA use: <b>'+fmt(record.annualUseM3)+' m³</b>. Component check: '+record.annualUseComponentsM3.map(fmt).join(' + ')+' = '+fmt(record.annualUseM3)+' m³.</p>'+(result?'<p><b>Your proposed plant demand:</b> '+fmt(result.dailyDemandM3)+' m³/day × calendar days = '+fmt(result.annualDemandM3)+' m³ in '+record.year+'. This equals '+result.annualDemandPercentOfReportedUse.toLocaleString('en-GB',{maximumSignificantDigits:4})+'% of reported annual system use; this ratio does not measure spare supply or ecological strain.</p><details><summary>Show monthly public figures and calculation evidence</summary><p>Plant intake = MW × 24 × operating fraction × (feed ÷ recovery fraction + utility intake) ÷ kWh/kg. Monthly intake multiplies this by calendar days. Stored and useful volumes below are stocks, never daily flow allowances.</p><div class="tablewrap"><table><thead><tr><th>Month</th><th>Stored hm³</th><th>Useful hm³</th><th>Proposed intake m³/month</th><th>Allocatable budget</th></tr></thead><tbody>'+result.monthly.map(p=>'<tr><td>'+esc(p.month)+'</td><td>'+fmt(p.storedHm3)+'</td><td>'+fmt(p.usefulHm3)+'</td><td>'+fmt(p.plantDemandM3)+'</td><td>Not established</td></tr>').join('')+'</tbody></table></div><p>Observed stock change ('+esc(result.storageChangePeriod)+'): '+fmt(record.monthly.at(-1).storedHm3)+' − '+fmt(record.monthly[0].storedHm3)+' = '+fmt(result.storageChangeHm3)+' hm³. This net change does not identify gross inflow or available abstraction.</p><p>PDF SHA-256: <code>'+esc(record.source.sha256)+'</code>. Downloaded '+esc(record.source.retrieved)+'. Source-value reproduction and arithmetic checks: <a href="VERIFICATION_PUBLIC_BUDGET.txt">verification receipt</a>.</p></details>':'<p>'+esc(error)+'</p>')+'<details><summary>Why an automatic spare-water budget is withheld</summary><ul>'+record.missing.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul><p>The software does not divide stored volume by days or replace annual use with a dry-season rate. No water inputs in the scenario form are silently filled.</p></details><button class="secondary publicReceipt">Export public calculation evidence ↓</button>';
 box.querySelector('.publicReceipt').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}));a.href=u;a.download='public-water-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 }}
 window.refreshPublicEvidence=render;
 document.addEventListener('input',render);
 fetch('data/public_budget.json').then(r=>{if(!r.ok)throw Error('Public evidence unavailable');return r.json();}).then(j=>{data=j;render();}).catch(err=>{document.getElementById('publicEvidenceA').textContent=err.message+'; water budget remains unestablished.';});
})();
